"""empty message

Revision ID: 387a9a9a1ee3
Revises: b8b8005d81a5
Create Date: 2023-10-23 12:46:22.172814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387a9a9a1ee3'
down_revision = 'b8b8005d81a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_full_name')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=128), nullable=False))
        batch_op.create_index('ix_user_full_name', ['full_name'], unique=False)

    # ### end Alembic commands ###
