"""empty message

Revision ID: a15218e43557
Revises: 387a9a9a1ee3
Create Date: 2023-10-23 13:14:10.790883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a15218e43557'
down_revision = '387a9a9a1ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    op.drop_table('status')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('isCompleted')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('isCompleted', sa.BOOLEAN(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'])
        batch_op.drop_column('deadline')

    op.create_table('status',
    sa.Column('status_id', sa.INTEGER(), nullable=False),
    sa.Column('desc', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('status_id')
    )
    op.create_table('project',
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('desc', sa.VARCHAR(length=128), nullable=False),
    sa.Column('deadline', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('status_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['status.status_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    # ### end Alembic commands ###
