"""Add desc to Project

Revision ID: a1943fafec59
Revises: 8e42883fda3f
Create Date: 2023-10-23 14:06:31.423077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1943fafec59'
down_revision = '8e42883fda3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('priority', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', sa.String(length=64), nullable=True))
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('priority', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('desc')

    # ### end Alembic commands ###
