"""add col full name

Revision ID: e61aafe976b1
Revises: 65a1a33cad8c
Create Date: 2023-09-25 15:34:59.022043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61aafe976b1'
down_revision = '65a1a33cad8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=128), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_full_name'), ['full_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_full_name'))
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
